//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationCodeMissingUniqueData
    {
        public string REG_NO { get; set; }
        public string SOURCE { get; set; }
        public string NAME { get; set; }
        public string FATHER_NAME { get; set; }
        public string DOB { get; set; }
        public string GENDER { get; set; }
        public string ADDR1 { get; set; }
        public string CITY1 { get; set; }
        public string PINCODE1 { get; set; }
        public string ADDR2 { get; set; }
        public string CITY2 { get; set; }
        public string PINCODE2 { get; set; }
        public string PRES_RLO { get; set; }
        public string RERM_RLO { get; set; }
        public string PHONE1 { get; set; }
        public string PHONE2 { get; set; }
        public string EPICNO { get; set; }
        public string BENMARITALSTATUS { get; set; }
        public string EMAIL { get; set; }
        public string DEPTLOCNAME { get; set; }
        public string DEPTLOCWARD { get; set; }
        public string ACCSTATUS { get; set; }
        public string BENAGE { get; set; }
        public string BENPLACEORBIRTH { get; set; }
        public string BENBPLSTATUS { get; set; }
        public string BENBPLNO { get; set; }
        public string BENAADHAARNO { get; set; }
        public string BENADDONAADHAAR { get; set; }
        public string BENRATIONCARDNO { get; set; }
        public string BENRATIONADDRESS { get; set; }
        public string BENVOTERCARDNO { get; set; }
        public string BENVOTERCARDADDRESS { get; set; }
        public string BENNATIONALITY { get; set; }
        public string BENRELIGION { get; set; }
        public string BENCASTE { get; set; }
        public string BENSUBCASTE { get; set; }
        public string BENCOUNTRY { get; set; }
        public string BENSTATE { get; set; }
        public string BENDISTRICT { get; set; }
        public string BENRURALURBAN { get; set; }
        public string BENSUBDIVISION { get; set; }
        public string BENBLOCK { get; set; }
        public string BLOCK_MUNICIPALITY_CORP_NAME { get; set; }
        public string BENGRAMPANCHAYAT { get; set; }
        public string BENVILLAGE { get; set; }
        public string BENWARD { get; set; }
        public string BENPOSTOFFICE { get; set; }
        public string BENPOLICESTATION { get; set; }
        public string BENPRECOUNTRY { get; set; }
        public string BENPRESTATE { get; set; }
        public string BENPREDISTRICT { get; set; }
        public string BENPRERURALURBAN { get; set; }
        public string BENPRESUBDIVISION { get; set; }
        public string BENPREGRAMPANCHAYAT { get; set; }
        public string BENPREVILLAGE { get; set; }
        public string BENPREMUNCORP { get; set; }
        public string BENPREPOSTOFFICE { get; set; }
        public string BENPREPOLICESTATION { get; set; }
        public string BENOCCUPATION { get; set; }
        public string BENADDRESSESTABLIS { get; set; }
        public string BENPFNUMBER { get; set; }
        public string BENESINUMBER { get; set; }
        public string BENBANKNAME { get; set; }
        public string BENBANKTYPE { get; set; }
        public string BENBANKACCNO { get; set; }
        public string BENBANKIFSCCODE { get; set; }
        public string BENBANKBRANCHDTLS { get; set; }
        public string BENBANKACCSTATUS { get; set; }
        public string BENNOMINEENAME { get; set; }
        public string BENNOMINEEDOB { get; set; }
        public string BENNOMINEEGENDER { get; set; }
        public string BENNOMINEEAGE { get; set; }
        public string BENNOMINEEAADHAARNO { get; set; }
        public string BENNOMINEERELATION { get; set; }
        public string BENNOMINEEADDRESS { get; set; }
        public string IFSC_CODE { get; set; }
        public string BRANCH_DETAILS { get; set; }
        public string PARTICULARS_OF_DOCUMENTS { get; set; }
        public string STATUS_OF_TRANSPORT_WORKER { get; set; }
        public string NATURE_OF_VEHICLE { get; set; }
        public string NATURE_OF_DUTY { get; set; }
        public string CERTIFICATE_OF_IDENTIFICATION { get; set; }
        public string DATE_OF_APPLICATION { get; set; }
        public string PLACE_OF_APPLICATION { get; set; }
        public string REGISTRATION_RENEWAL { get; set; }
        public string DATE_OF_REGISRATION_RENEWAL { get; set; }
        public string AMOUNT_PAID { get; set; }
        public string DATE_OF_PAYMENT { get; set; }
        public string DATE_OF_REGISTRATION { get; set; }
        public string SSINNO { get; set; }
        public int ID { get; set; }
        public Nullable<System.DateTime> NEW_DOB { get; set; }
        public Nullable<System.DateTime> NEW_DOR { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
    }
}
