//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAttachement
    {
        public long AttachmentId { get; set; }
        public Nullable<long> ClaimType { get; set; }
        public Nullable<long> TransactionId { get; set; }
        public string FileName { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreadtedDate { get; set; }
        public byte[] FileContent { get; set; }
        public string FilePath { get; set; }
        public Nullable<long> AttachmentType { get; set; }
        public Nullable<int> Source { get; set; }
    
        public virtual TblClaimConfigHdr TblClaimConfigHdr { get; set; }
        public virtual TblLOVDtl TblLOVDtl { get; set; }
    }
}
