//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAgentAdditionalData
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string Pincode { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public string AccountNumber { get; set; }
        public string IfscCode { get; set; }
        public string AadharNumber { get; set; }
        public string AadharFile { get; set; }
        public string PanNumber { get; set; }
        public string PanFile { get; set; }
        public string BankDDFile { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Reason { get; set; }
        public string Marital { get; set; }
        public string RelName { get; set; }
        public string Photo { get; set; }
        public string Signature { get; set; }
        public Nullable<int> AgentType { get; set; }
        public string BankType { get; set; }
        public string CasteCode { get; set; }
        public Nullable<System.DateTime> AgreementDate { get; set; }
    }
}
