//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBenScheme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblBenScheme()
        {
            this.TblBenSchemesDtls = new HashSet<TblBenSchemesDtl>();
        }
    
        public int SchemeBenId { get; set; }
        public long BenId { get; set; }
        public int SchemeId { get; set; }
        public int SchemeStatus { get; set; }
        public string SchemeRemarks { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual TblBenScheme TblBenSchemes1 { get; set; }
        public virtual TblBenScheme TblBenScheme1 { get; set; }
        public virtual TblSchemeMst TblSchemeMst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblBenSchemesDtl> TblBenSchemesDtls { get; set; }
    }
}
