//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBoardUser
    {
        public int BoardUserId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> BoardId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreadtedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpadtedDate { get; set; }
    
        public virtual TblBoard TblBoard { get; set; }
        public virtual TblNewReg TblNewReg { get; set; }
    }
}
