//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBenNomineeDtls5thSet
    {
        public int BenNomineeSno { get; set; }
        public long BenSno { get; set; }
        public string BenNomineeName { get; set; }
        public string BenNomineeRelation { get; set; }
        public string BenNomineeGender { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string BenNomineeAge { get; set; }
        public string BenNomineeShareAllocation { get; set; }
        public string BenNomineeBankName { get; set; }
        public string BenNomineeBankAccNo { get; set; }
        public string BenNomineeBankBranch { get; set; }
        public string BenNomineeBankIfscCode { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> RelationshipID { get; set; }
        public string RegNo { get; set; }
        public Nullable<long> NewBenSno { get; set; }
    }
}
