//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBlockDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblBlockDetail()
        {
            this.TblFundRequestDtl1 = new HashSet<TblFundRequestDtl1>();
        }
    
        public int BlockSno { get; set; }
        public int SubDivisionSno { get; set; }
        public int TypeOfData { get; set; }
        public string BlockName { get; set; }
        public string Code { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public string DistrictName { get; set; }
        public Nullable<int> SubDivisionId { get; set; }
        public string SubDivisionName { get; set; }
        public string LocationCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFundRequestDtl1> TblFundRequestDtl1 { get; set; }
    }
}
