//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBenAddressIssues2
    {
        public long BenAddressSno { get; set; }
        public long BenSno { get; set; }
        public string BenAddressType { get; set; }
        public string BenState { get; set; }
        public Nullable<int> BenDistrict { get; set; }
        public Nullable<int> BenSubDivision { get; set; }
        public Nullable<int> LocationType { get; set; }
        public Nullable<int> BenBmc { get; set; }
        public string BenVsr { get; set; }
        public string BenAddressLine1 { get; set; }
        public string BenGpWard { get; set; }
        public Nullable<int> BenPs { get; set; }
        public Nullable<int> BenPo { get; set; }
        public string BenPincode { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
