//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBenSchemesDtl
    {
        public int SchemeBenDtlsId { get; set; }
        public int SchemeBenId { get; set; }
        public string WorkerType { get; set; }
        public string NatureOfVehicle { get; set; }
        public string NatureOfDutes { get; set; }
        public string NameAndAddressOfAuth { get; set; }
        public string AddressOfEstablishment { get; set; }
        public string Description { get; set; }
        public string RegNoOfEstablishment { get; set; }
        public Nullable<System.DateTime> DateOfJoining { get; set; }
        public Nullable<System.DateTime> DateOfRelieving { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual TblBenScheme TblBenScheme { get; set; }
    }
}
