//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBeneficiaryDuplicate
    {
        public long BenSno { get; set; }
        public string BenSalutation { get; set; }
        public string BenFirstName { get; set; }
        public string BenLastName { get; set; }
        public string BenMiddleName { get; set; }
        public Nullable<System.DateTime> BenDob { get; set; }
        public Nullable<int> BenAge { get; set; }
        public string BenGender { get; set; }
        public string BenMaritalStatus { get; set; }
        public string BenFatherFirstName { get; set; }
        public string HusbandName { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> BenRegDate { get; set; }
        public string BenIdCardType { get; set; }
        public string BenIdCardNo { get; set; }
        public string BenReligion { get; set; }
        public string BenSocialCategory { get; set; }
        public Nullable<bool> BenBplStatus { get; set; }
        public string BenBplNo { get; set; }
        public string BenOccupation { get; set; }
        public string BenMobileNo { get; set; }
        public Nullable<bool> BenAddressType { get; set; }
        public string BenProvisionType { get; set; }
        public string BenProvisionNo { get; set; }
        public string BenEmpType { get; set; }
        public string BenSelfEmployed { get; set; }
        public string BenEstablishedAddress { get; set; }
        public string BenMonthlyIncom { get; set; }
        public Nullable<int> BankDist { get; set; }
        public Nullable<int> BankLoc { get; set; }
        public string BenBankName { get; set; }
        public string BenBankBranch { get; set; }
        public string BenBankAccNo { get; set; }
        public string BenBankIfscCode { get; set; }
        public string BenSsinCode { get; set; }
        public string BenUserId { get; set; }
        public string BenUserKey { get; set; }
        public string BenUserPwd { get; set; }
        public string BenIssuingAuth { get; set; }
        public string BenIssuingAuthName { get; set; }
        public string BenPhoto { get; set; }
        public string BenSignature { get; set; }
        public string BenPassBook { get; set; }
        public string BenIdentity { get; set; }
        public string BenForm { get; set; }
        public bool IsActive { get; set; }
        public string RegNumber { get; set; }
        public string RegType { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public int Status { get; set; }
        public string Remarks { get; set; }
        public string BenEsiNumber { get; set; }
        public Nullable<int> BenPFStatus { get; set; }
        public string AadharCard { get; set; }
        public string EpicCard { get; set; }
        public string BankAccNo { get; set; }
        public string BenAadhar { get; set; }
        public string BengaliName { get; set; }
        public string BenTempRegNo { get; set; }
        public string IfscReason { get; set; }
        public string SSI_Number { get; set; }
        public long ID { get; set; }
        public string RegistrationPhotoCopy { get; set; }
        public string SchemeCertificate { get; set; }
        public Nullable<System.DateTime> VerifyDate { get; set; }
        public string AuthorityLocation { get; set; }
        public string SalFather { get; set; }
        public string SalHusband { get; set; }
        public string IsUnique { get; set; }
        public Nullable<int> NoOfRecords { get; set; }
        public string CommentsByInspector { get; set; }
        public string RejectedDocumnet { get; set; }
        public string IsDedupeDone { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<int> LoginCounts { get; set; }
        public Nullable<int> LoginStatus { get; set; }
        public Nullable<int> ReviveStatus { get; set; }
        public string BenOtherDoc { get; set; }
        public Nullable<int> BenDistrict { get; set; }
        public Nullable<int> BenSubDivision { get; set; }
        public Nullable<int> BenBmc { get; set; }
        public string DataType { get; set; }
        public string Part1 { get; set; }
        public string Part2 { get; set; }
        public Nullable<System.DateTime> Part2CreatedDate { get; set; }
        public Nullable<System.DateTime> FinalActionDate { get; set; }
        public string MotherName { get; set; }
        public string BeneType { get; set; }
        public string Part2CreatedBy { get; set; }
        public Nullable<System.DateTime> FirstAppliedDate { get; set; }
        public int ReApplyCount { get; set; }
        public string FatherFName { get; set; }
        public string FatherMName { get; set; }
        public string FatherLName { get; set; }
        public Nullable<System.DateTime> DedupeStartDateTime { get; set; }
        public Nullable<System.DateTime> DedupeEndDateTime { get; set; }
        public Nullable<int> RowCount { get; set; }
    }
}
