//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBlockDetailsold
    {
        public int BlockSno { get; set; }
        public int SubDivisionSno { get; set; }
        public int TypeOfData { get; set; }
        public string BlockName { get; set; }
        public string Code { get; set; }
    }
}
