//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBankBranch
    {
        public int BankBranchSno { get; set; }
        public int BankCenterSno { get; set; }
        public string BankBranchName { get; set; }
        public string BankIfscCode { get; set; }
        public string BankAddress { get; set; }
    }
}
