//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBenPFInterestRegister
    {
        public long BenInterestId { get; set; }
        public Nullable<long> BenPFAccountId { get; set; }
        public Nullable<long> BenSno { get; set; }
        public Nullable<System.DateTime> InterestDate { get; set; }
        public Nullable<decimal> InterestAmount { get; set; }
        public Nullable<int> FinancialYearId { get; set; }
        public Nullable<long> ID { get; set; }
        public string PF_NO { get; set; }
        public string AGENT_ARN_NO { get; set; }
        public string REF_TABLE_ID { get; set; }
        public Nullable<decimal> CURRENT_BALANCE { get; set; }
        public string RECEIPT_NO { get; set; }
        public string BOOK_NO { get; set; }
        public Nullable<int> FOR_MONTH { get; set; }
        public string FOR_YEAR { get; set; }
        public string REMARKS { get; set; }
        public string BN_REMARKS { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<System.DateTime> TX_DATE { get; set; }
        public string TX_TYPE { get; set; }
        public string PRINTED { get; set; }
        public string LAST_PRINTED { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<System.DateTime> BENEF_REGIS_DATE { get; set; }
        public string BREAKUP_ID { get; set; }
    }
}
