//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBankCenter
    {
        public int BankCenterSno { get; set; }
        public Nullable<int> BankSno { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public string BankCenter { get; set; }
    }
}
