//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBeneficiaryPFAccount
    {
        public string BeneficiaryPFAccountNO { get; set; }
        public long BenSno { get; set; }
        public Nullable<bool> PFAccountLegacy { get; set; }
        public Nullable<System.DateTime> PFRegistrationDate { get; set; }
        public Nullable<int> PFStatus { get; set; }
        public Nullable<System.DateTime> PFLockingPeriodDate { get; set; }
        public string LegacyReferType { get; set; }
        public Nullable<long> LegacyReferNO { get; set; }
        public Nullable<bool> CoveredUnder1952ESI { get; set; }
        public string NewOrLegacy { get; set; }
        public Nullable<System.DateTime> MaturityDate { get; set; }
        public long BenPFAccountId { get; set; }
        public Nullable<int> Source { get; set; }
    }
}
