//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBenPFGovtContributionRegister
    {
        public long BenPFGovtContributionId { get; set; }
        public Nullable<long> BenPFAccountId { get; set; }
        public Nullable<long> BenSno { get; set; }
        public Nullable<System.DateTime> ContributionDate { get; set; }
        public Nullable<decimal> ContributionAmount { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
    
        public virtual TblBeneficiary TblBeneficiary { get; set; }
    }
}
