//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblClaimStatu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblClaimStatu()
        {
            this.TblApprovalPermissions = new HashSet<TblApprovalPermission>();
            this.TblDeaths = new HashSet<TblDeath>();
            this.TblEducationHdrs = new HashSet<TblEducationHdr>();
            this.TblFundRequestHdrs = new HashSet<TblFundRequestHdr>();
            this.TblProvidentFunds = new HashSet<TblProvidentFund>();
            this.TblWorkFlowTransactions = new HashSet<TblWorkFlowTransaction>();
        }
    
        public int StatusId { get; set; }
        public string StatusName { get; set; }
        public Nullable<int> WFDtlId { get; set; }
        public Nullable<int> WFId { get; set; }
        public string ActionName { get; set; }
        public Nullable<int> NextWFDtlId { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblApprovalPermission> TblApprovalPermissions { get; set; }
        public virtual TblWorkFlowDtl TblWorkFlowDtl { get; set; }
        public virtual TblWorkFlowHdr TblWorkFlowHdr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeath> TblDeaths { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEducationHdr> TblEducationHdrs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFundRequestHdr> TblFundRequestHdrs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblProvidentFund> TblProvidentFunds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblWorkFlowTransaction> TblWorkFlowTransactions { get; set; }
    }
}
