//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCheckListHdr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblCheckListHdr()
        {
            this.TblCheckListDtls = new HashSet<TblCheckListDtl>();
        }
    
        public int CheckListHdrId { get; set; }
        public string Name { get; set; }
        public Nullable<long> CategoryId { get; set; }
        public string Option { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCheckListDtl> TblCheckListDtls { get; set; }
        public virtual TblClaimConfigHdr TblClaimConfigHdr { get; set; }
    }
}
