//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCheckListDtl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblCheckListDtl()
        {
            this.TblDeathCheckListDetails = new HashSet<TblDeathCheckListDetail>();
            this.TblDisabilityCheckListDetails = new HashSet<TblDisabilityCheckListDetail>();
            this.TblEducationCheckListDetails = new HashSet<TblEducationCheckListDetail>();
            this.TblHealthFamilyCheckListDetails = new HashSet<TblHealthFamilyCheckListDetail>();
            this.TblProvidentFundCheckListDetails = new HashSet<TblProvidentFundCheckListDetail>();
        }
    
        public int CheckListDtlId { get; set; }
        public Nullable<int> CheckListHdrId { get; set; }
        public string Name { get; set; }
    
        public virtual TblCheckListHdr TblCheckListHdr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeathCheckListDetail> TblDeathCheckListDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDisabilityCheckListDetail> TblDisabilityCheckListDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEducationCheckListDetail> TblEducationCheckListDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblHealthFamilyCheckListDetail> TblHealthFamilyCheckListDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblProvidentFundCheckListDetail> TblProvidentFundCheckListDetails { get; set; }
    }
}
