//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblClaimConfigHdr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblClaimConfigHdr()
        {
            this.TblAttachements = new HashSet<TblAttachement>();
            this.TblCheckListHdrs = new HashSet<TblCheckListHdr>();
            this.TblClaimConfigDtls = new HashSet<TblClaimConfigDtl>();
            this.TblDeaths = new HashSet<TblDeath>();
            this.TblEducationHdrs = new HashSet<TblEducationHdr>();
            this.TblFundReleaseOrderDtls = new HashSet<TblFundReleaseOrderDtl>();
            this.TblFundRequestDtl2 = new HashSet<TblFundRequestDtl2>();
            this.TblProvidentFunds = new HashSet<TblProvidentFund>();
            this.TblWorkFlowTransactions = new HashSet<TblWorkFlowTransaction>();
        }
    
        public long ClaimMasterId { get; set; }
        public string ClaimName { get; set; }
        public Nullable<System.DateTime> CliamEffectiveDate { get; set; }
        public string ClaimDescription { get; set; }
        public Nullable<bool> IsAnnualLimit { get; set; }
        public Nullable<decimal> AnnualLimit { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblAttachement> TblAttachements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCheckListHdr> TblCheckListHdrs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblClaimConfigDtl> TblClaimConfigDtls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeath> TblDeaths { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEducationHdr> TblEducationHdrs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFundReleaseOrderDtl> TblFundReleaseOrderDtls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFundRequestDtl2> TblFundRequestDtl2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblProvidentFund> TblProvidentFunds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblWorkFlowTransaction> TblWorkFlowTransactions { get; set; }
    }
}
