//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblClaim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblClaim()
        {
            this.TblDeaths = new HashSet<TblDeath>();
            this.TblDeathClaimExceptionDetails = new HashSet<TblDeathClaimExceptionDetail>();
            this.TblDisabilityClaimExceptionDetails = new HashSet<TblDisabilityClaimExceptionDetail>();
            this.TblEducationClaimExceptionDetails = new HashSet<TblEducationClaimExceptionDetail>();
            this.TblEducationHdrs = new HashSet<TblEducationHdr>();
            this.TblHealthFamilyClaimExceptionDetails = new HashSet<TblHealthFamilyClaimExceptionDetail>();
            this.TblProvidentFunds = new HashSet<TblProvidentFund>();
            this.TblProvidentFundClaimExceptionDetails = new HashSet<TblProvidentFundClaimExceptionDetail>();
        }
    
        public long ClaimId { get; set; }
        public Nullable<long> BenSno { get; set; }
        public Nullable<long> EntryPoint { get; set; }
        public Nullable<long> ReasonforApply { get; set; }
        public string SSIN { get; set; }
        public string NomineeName { get; set; }
        public string NomineeAddress { get; set; }
        public Nullable<long> NomineeContact { get; set; }
        public Nullable<System.DateTime> NomineeDOB { get; set; }
        public string NomineeBankAccount { get; set; }
        public string NomineeIFSCCode { get; set; }
        public Nullable<int> NomineeRelationwithBen { get; set; }
        public Nullable<int> NomineeId { get; set; }
        public Nullable<long> ClaimSubmittedBy { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreadtedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpadtedDate { get; set; }
        public Nullable<int> FinancialYear { get; set; }
    
        public virtual TblBenNomineeDtl TblBenNomineeDtl { get; set; }
        public virtual TblLOVDtl TblLOVDtl { get; set; }
        public virtual TblFinancialYear TblFinancialYear { get; set; }
        public virtual TblLOVDtl TblLOVDtl1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeath> TblDeaths { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeathClaimExceptionDetail> TblDeathClaimExceptionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDisabilityClaimExceptionDetail> TblDisabilityClaimExceptionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEducationClaimExceptionDetail> TblEducationClaimExceptionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEducationHdr> TblEducationHdrs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblHealthFamilyClaimExceptionDetail> TblHealthFamilyClaimExceptionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblProvidentFund> TblProvidentFunds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblProvidentFundClaimExceptionDetail> TblProvidentFundClaimExceptionDetails { get; set; }
        public virtual TblBeneficiary TblBeneficiary { get; set; }
    }
}
