//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblClaimConfigDtl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblClaimConfigDtl()
        {
            this.TblDeaths = new HashSet<TblDeath>();
            this.TblProvidentFunds = new HashSet<TblProvidentFund>();
            this.TblEducationDtls = new HashSet<TblEducationDtl>();
        }
    
        public long ClaimConfigId { get; set; }
        public string ClaimConfigOptionName { get; set; }
        public Nullable<bool> IsAnnualLimit { get; set; }
        public Nullable<decimal> AnnualLimit { get; set; }
        public Nullable<long> ClaimMasterId { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual TblClaimConfigHdr TblClaimConfigHdr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeath> TblDeaths { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblProvidentFund> TblProvidentFunds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEducationDtl> TblEducationDtls { get; set; }
    }
}
