//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDisabilityCheckListDetail
    {
        public long ID { get; set; }
        public long ClaimId { get; set; }
        public int CheckListDtlId { get; set; }
        public string Option { get; set; }
    
        public virtual TblCheckListDtl TblCheckListDtl { get; set; }
    }
}
