//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDuplicateCardsGenerated
    {
        public int Sno { get; set; }
        public Nullable<int> Bensno { get; set; }
        public string BenTempRegNo { get; set; }
        public string SSIN { get; set; }
        public string Scheme { get; set; }
        public string RegNumber { get; set; }
        public string BenRegDate { get; set; }
        public string ApplicantName { get; set; }
        public string FatherName { get; set; }
        public string BenDOB { get; set; }
        public string BenMobileNo { get; set; }
        public string AadharCard { get; set; }
        public string EpicCard { get; set; }
        public string BankAccNo { get; set; }
        public string DistrictName { get; set; }
        public string SubDivisionName { get; set; }
        public string BlockName { get; set; }
        public Nullable<System.DateTime> RunDateTime { get; set; }
        public Nullable<int> Id { get; set; }
        public string BenPhotoPath { get; set; }
        public string HusbandName { get; set; }
    }
}
