//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDownlaodRequest
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public System.DateTime FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string Districts { get; set; }
        public string SubDivisions { get; set; }
        public string Locations { get; set; }
        public Nullable<int> Status { get; set; }
        public string Application_Status { get; set; }
        public string Report_Name { get; set; }
        public string Url { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Scheme { get; set; }
        public string USerType { get; set; }
        public string UserRole { get; set; }
        public string Users { get; set; }
        public string Value { get; set; }
        public Nullable<long> Counts { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public string FromSubmitStatus { get; set; }
        public string GpList { get; set; }
        public string PsList { get; set; }
        public string PoList { get; set; }
        public string Religion { get; set; }
        public Nullable<int> FileSaveStatus { get; set; }
        public string DownLoadPath { get; set; }
    }
}
