//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDeath
    {
        public long DeathId { get; set; }
        public Nullable<long> ClaimId { get; set; }
        public string ClaimRefernceNo { get; set; }
        public Nullable<System.DateTime> DateofDeath { get; set; }
        public Nullable<long> NatureofDeath { get; set; }
        public string PlaceofDeath { get; set; }
        public string DetailsofDeath { get; set; }
        public Nullable<decimal> ClaimAmount { get; set; }
        public Nullable<decimal> ApprovedAmount { get; set; }
        public Nullable<bool> IsDeathorpermanentdisabilitynotcausedbyinjuries { get; set; }
        public Nullable<bool> IsDeathorpermanentdisabilitynotcausedbyintentional { get; set; }
        public Nullable<bool> IsOtherFinancialAssistance { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreadtedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpadtedDate { get; set; }
        public Nullable<long> ClaimType { get; set; }
        public string InspectorComments { get; set; }
        public string ALCComments { get; set; }
        public string DLCComments { get; set; }
        public string ExceptionComments { get; set; }
        public Nullable<int> PaymentStatusId { get; set; }
        public Nullable<System.DateTime> PaymentReleaseDate { get; set; }
        public Nullable<long> FundRequestId { get; set; }
        public Nullable<long> PaymentProcessingId { get; set; }
        public Nullable<System.DateTime> PaymentProcessingDate { get; set; }
        public Nullable<System.DateTime> FundRequisitionDate { get; set; }
        public Nullable<long> PaymentReleaseId { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public Nullable<System.DateTime> SendbackFromInspectorDate { get; set; }
        public Nullable<System.DateTime> ForwardedToALCDate { get; set; }
        public Nullable<System.DateTime> SendbackFromALCDate { get; set; }
        public Nullable<System.DateTime> RejectFromALCDate { get; set; }
        public Nullable<System.DateTime> ApprovedByALCDate { get; set; }
        public Nullable<System.DateTime> ReferToALCDate { get; set; }
        public Nullable<System.DateTime> ReferedRejectByALCDate { get; set; }
        public Nullable<System.DateTime> ReferSendbackByALCDate { get; set; }
        public Nullable<System.DateTime> ReferApprovedByALCDate { get; set; }
        public Nullable<System.DateTime> ReferedToDLCDate { get; set; }
        public Nullable<System.DateTime> ReferSendbackFromDLCDate { get; set; }
        public Nullable<System.DateTime> ReferedRejectByDLCDate { get; set; }
        public Nullable<System.DateTime> ReferApprovedByDLCDate { get; set; }
        public Nullable<System.DateTime> ForcedClosedDate { get; set; }
        public Nullable<System.DateTime> ApprovedByDLCDate { get; set; }
        public Nullable<System.DateTime> RejectFromDLCDate { get; set; }
        public string BoardComments { get; set; }
        public string TreasurerComments { get; set; }
        public string InspChronologicalOrderComments { get; set; }
        public string ALCChronologicalOrderComments { get; set; }
        public string DLCChronologicalOrderComments { get; set; }
    
        public virtual TblClaim TblClaim { get; set; }
        public virtual TblClaimConfigDtl TblClaimConfigDtl { get; set; }
        public virtual TblClaimConfigHdr TblClaimConfigHdr { get; set; }
        public virtual TblClaimStatu TblClaimStatu { get; set; }
        public virtual TblFundRequestHdr TblFundRequestHdr { get; set; }
        public virtual TblPaymentProcessingHdr TblPaymentProcessingHdr { get; set; }
        public virtual TblPaymentReleaseHdr TblPaymentReleaseHdr { get; set; }
    }
}
