//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEditNomDep
    {
        public int Id { get; set; }
        public Nullable<int> BenSno { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> VerfiedDate { get; set; }
        public Nullable<int> VerfiedBy { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remarks { get; set; }
    }
}
