//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEducationDtl
    {
        public long EducationDtlId { get; set; }
        public Nullable<long> EducationHdrId { get; set; }
        public Nullable<int> DependentId { get; set; }
        public string InstitutionName { get; set; }
        public string InstitutionPrinicipleName { get; set; }
        public Nullable<long> InstitutionContact { get; set; }
        public string RegistrationRollNo { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<System.DateTime> DateofAdmission { get; set; }
        public Nullable<long> LastExamPassed { get; set; }
        public Nullable<long> PresentlyReading { get; set; }
        public Nullable<decimal> EligibleAmount { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> IsMarried { get; set; }
    
        public virtual TblBenFamilyMember TblBenFamilyMember { get; set; }
        public virtual TblClaimConfigDtl TblClaimConfigDtl { get; set; }
        public virtual TblEducationHdr TblEducationHdr { get; set; }
        public virtual TblLOVDtl TblLOVDtl { get; set; }
    }
}
