//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEducationClaimExceptionDetail
    {
        public long ID { get; set; }
        public long ClaimId { get; set; }
        public string ExceptionText { get; set; }
        public Nullable<System.DateTime> ExceptionCapturedDate { get; set; }
        public Nullable<long> RaisedBy { get; set; }
    
        public virtual TblClaim TblClaim { get; set; }
    }
}
