//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFundReleaseOrderHdr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblFundReleaseOrderHdr()
        {
            this.TblFundReleaseOrderDtls = new HashSet<TblFundReleaseOrderDtl>();
            this.TblPaymentProcessingHdrs = new HashSet<TblPaymentProcessingHdr>();
            this.TblUtilizationCertificateDtls = new HashSet<TblUtilizationCertificateDtl>();
        }
    
        public long FundReleaseOrderHdrId { get; set; }
        public long FundRequestId { get; set; }
        public Nullable<int> RLOOfficeID { get; set; }
        public Nullable<System.DateTime> FundReleaseDate { get; set; }
        public Nullable<decimal> FundSanctioned { get; set; }
        public Nullable<decimal> FundReleased { get; set; }
        public Nullable<int> FundRequestType { get; set; }
        public string ReleaseOrderNumber { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> RLOBankAccountId { get; set; }
        public Nullable<bool> UtilizationStatus { get; set; }
        public Nullable<int> FinancialYearId { get; set; }
        public Nullable<int> ReleaseType { get; set; }
    
        public virtual TblFinancialYear TblFinancialYear { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFundReleaseOrderDtl> TblFundReleaseOrderDtls { get; set; }
        public virtual TblFundRequestHdr TblFundRequestHdr { get; set; }
        public virtual TblRLOOffice TblRLOOffice { get; set; }
        public virtual TblRLOOfficeBank TblRLOOfficeBank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblPaymentProcessingHdr> TblPaymentProcessingHdrs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblUtilizationCertificateDtl> TblUtilizationCertificateDtls { get; set; }
    }
}
