//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFundRequestDtl2
    {
        public long FundRequestDtl2Id { get; set; }
        public Nullable<long> FundRequestId { get; set; }
        public Nullable<long> ClaimId { get; set; }
        public Nullable<long> ClaimConfigId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> PaymentStatus { get; set; }
    
        public virtual TblClaimConfigHdr TblClaimConfigHdr { get; set; }
        public virtual TblFundRequestHdr TblFundRequestHdr { get; set; }
    }
}
