//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFundRequestDtl1
    {
        public long FundRequestDtl1Id { get; set; }
        public Nullable<long> FundRequestId { get; set; }
        public Nullable<int> LocationId { get; set; }
    
        public virtual TblFundRequestHdr TblFundRequestHdr { get; set; }
        public virtual TblBlockDetail TblBlockDetail { get; set; }
    }
}
