//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFundRequestHdr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblFundRequestHdr()
        {
            this.TblDeaths = new HashSet<TblDeath>();
            this.TblEducationHdrs = new HashSet<TblEducationHdr>();
            this.TblFundReleaseOrderHdrs = new HashSet<TblFundReleaseOrderHdr>();
            this.TblFundRequestDtl1 = new HashSet<TblFundRequestDtl1>();
            this.TblFundRequestDtl2 = new HashSet<TblFundRequestDtl2>();
            this.TblFundRequestExpensesDtls = new HashSet<TblFundRequestExpensesDtl>();
            this.TblProvidentFunds = new HashSet<TblProvidentFund>();
        }
    
        public long FundRequestHdrId { get; set; }
        public Nullable<int> RLOOfficeID { get; set; }
        public Nullable<System.DateTime> FundRequestDate { get; set; }
        public Nullable<System.DateTime> FundRequiredDate { get; set; }
        public Nullable<System.DateTime> FundApprovedDate { get; set; }
        public Nullable<System.DateTime> FundReleaseDate { get; set; }
        public Nullable<decimal> FundRequested { get; set; }
        public Nullable<decimal> FundSanctioned { get; set; }
        public Nullable<decimal> FundReleased { get; set; }
        public Nullable<int> FundRequestType { get; set; }
        public string ReleaseOrderNumber { get; set; }
        public string DLCComments { get; set; }
        public string BoardComments { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> BoardId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> SendBackByDLCDate { get; set; }
        public Nullable<System.DateTime> ForwardToBoardDate { get; set; }
        public Nullable<System.DateTime> SendBackByBoardDate { get; set; }
        public Nullable<System.DateTime> RejectByBoardDate { get; set; }
        public Nullable<int> RLOBankAccountId { get; set; }
        public Nullable<int> isAllClaimsStatus { get; set; }
        public Nullable<int> FinancialYearId { get; set; }
        public string DLCChronologicalOrderComments { get; set; }
        public string CEOChronologicalOrderComments { get; set; }
        public string ALCComments { get; set; }
    
        public virtual TblBoard TblBoard { get; set; }
        public virtual TblClaimStatu TblClaimStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeath> TblDeaths { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEducationHdr> TblEducationHdrs { get; set; }
        public virtual TblFinancialYear TblFinancialYear { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFundReleaseOrderHdr> TblFundReleaseOrderHdrs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFundRequestDtl1> TblFundRequestDtl1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFundRequestDtl2> TblFundRequestDtl2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFundRequestExpensesDtl> TblFundRequestExpensesDtls { get; set; }
        public virtual TblRLOOffice TblRLOOffice { get; set; }
        public virtual TblRLOOfficeBank TblRLOOfficeBank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblProvidentFund> TblProvidentFunds { get; set; }
    }
}
