//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFundRequestExpensesDtl
    {
        public long FundRequestExpensesDtlId { get; set; }
        public long FundRequestHdrId { get; set; }
        public Nullable<long> ItemId { get; set; }
        public Nullable<decimal> FundsRequired { get; set; }
        public Nullable<decimal> PhysicalTarget { get; set; }
        public Nullable<decimal> ExpenditureIncurredDuringLastFinYear { get; set; }
    
        public virtual TblFundRequestHdr TblFundRequestHdr { get; set; }
        public virtual TblLOVDtl TblLOVDtl { get; set; }
    }
}
