//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblHelp
    {
        public int Id { get; set; }
        public string Remarks { get; set; }
        public string Mail { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
