//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblHospital
    {
        public long HospitalId { get; set; }
        public string HospitalName { get; set; }
        public string HospitalAddressLine1 { get; set; }
        public string HospitalAddressLine2 { get; set; }
        public string HospitalCity { get; set; }
        public string HospitalContactNumber { get; set; }
        public string HospitalEmail { get; set; }
        public string HospitalContactPerson { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreadtedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpadtedDate { get; set; }
        public Nullable<long> HospitalCode { get; set; }
        public string HospitalType { get; set; }
        public string NotificaionNo { get; set; }
        public Nullable<System.DateTime> NotificationDate { get; set; }
        public Nullable<System.DateTime> ValidUpto { get; set; }
        public string FacilityAvailable { get; set; }
    }
}
