//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblHealthFamilyPackage
    {
        public long HealthFamilyPackagesId { get; set; }
        public Nullable<long> HealthFamilyId { get; set; }
        public Nullable<long> PackageID { get; set; }
    
        public virtual TblPackage TblPackage { get; set; }
    }
}
