//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLogin
    {
        public int Id { get; set; }
        public string UserType { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> LogoutDateTime { get; set; }
        public string SessionId { get; set; }
        public string Reason { get; set; }
        public Nullable<int> Status { get; set; }
        public string SystemIp { get; set; }
    }
}
