//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblListOfInd
    {
        public int ListIndSno { get; set; }
        public int IndType { get; set; }
        public string IndustryName { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime Createddate { get; set; }
    }
}
