//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLabel
    {
        public int Id { get; set; }
        public string Label_Name { get; set; }
        public string Bengali { get; set; }
        public string Hindi { get; set; }
    }
}
