//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLOVDtl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblLOVDtl()
        {
            this.TblAttachements = new HashSet<TblAttachement>();
            this.TblClaims = new HashSet<TblClaim>();
            this.TblClaims1 = new HashSet<TblClaim>();
            this.TblFundRequestExpensesDtls = new HashSet<TblFundRequestExpensesDtl>();
            this.TblEducationDtls = new HashSet<TblEducationDtl>();
        }
    
        public long LOVDtlId { get; set; }
        public string OptionName { get; set; }
        public Nullable<int> OrderValue { get; set; }
        public Nullable<long> LOVId { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblAttachement> TblAttachements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblClaim> TblClaims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblClaim> TblClaims1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFundRequestExpensesDtl> TblFundRequestExpensesDtls { get; set; }
        public virtual TblLOVHdr TblLOVHdr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEducationDtl> TblEducationDtls { get; set; }
    }
}
