//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMenu
    {
        public int ID { get; set; }
        public Nullable<int> MenuId { get; set; }
        public Nullable<int> SubMenuId { get; set; }
        public string MenuName { get; set; }
        public string MenuUrl { get; set; }
        public string Class { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> MofiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
