//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblNewReg
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblNewReg()
        {
            this.TblBoardUsers = new HashSet<TblBoardUser>();
            this.TblRLOOffices = new HashSet<TblRLOOffice>();
            this.TblRLOOfficeUsers = new HashSet<TblRLOOfficeUser>();
            this.TblUserGpWardMaps = new HashSet<TblUserGpWardMap>();
            this.UserDisMaps = new HashSet<UserDisMap>();
            this.UserLocationMaps = new HashSet<UserLocationMap>();
            this.UserSubDivMaps = new HashSet<UserSubDivMap>();
        }
    
        public int Userid { get; set; }
        public string UserCode { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Mobileno { get; set; }
        public string LandlineNumber { get; set; }
        public string Email { get; set; }
        public int UserType { get; set; }
        public string UserPwd { get; set; }
        public string SaltKey { get; set; }
        public Nullable<int> Location { get; set; }
        public Nullable<int> DistId { get; set; }
        public Nullable<int> SubDivId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> ChangePwd { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string Designation { get; set; }
        public string RegType { get; set; }
        public Nullable<System.DateTime> LoginDate { get; set; }
        public Nullable<long> LoginCounts { get; set; }
        public Nullable<int> LoginStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblBoardUser> TblBoardUsers { get; set; }
        public virtual TblUserType TblUserType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblRLOOffice> TblRLOOffices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblRLOOfficeUser> TblRLOOfficeUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblUserGpWardMap> TblUserGpWardMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserDisMap> UserDisMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLocationMap> UserLocationMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSubDivMap> UserSubDivMaps { get; set; }
    }
}
