//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOfflineRegReport
    {
        public int Id { get; set; }
        public string DistrictName { get; set; }
        public string SubDivisionName { get; set; }
        public Nullable<long> Legacy1 { get; set; }
        public Nullable<long> Lecgacy2 { get; set; }
        public Nullable<long> NewApplicationBasic { get; set; }
        public Nullable<long> NewApplicationFull { get; set; }
        public Nullable<long> Caf { get; set; }
        public Nullable<long> ReqId { get; set; }
    }
}
