//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPaymentProcessingHdr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblPaymentProcessingHdr()
        {
            this.TblDeaths = new HashSet<TblDeath>();
            this.TblEducationHdrs = new HashSet<TblEducationHdr>();
            this.TblPaymentReleaseHdrs = new HashSet<TblPaymentReleaseHdr>();
            this.TblProvidentFunds = new HashSet<TblProvidentFund>();
        }
    
        public long PaymentProcessingID { get; set; }
        public Nullable<long> FundRequestId { get; set; }
        public Nullable<int> RLOOfficeId { get; set; }
        public Nullable<System.DateTime> PaymentProcessingDate { get; set; }
        public Nullable<System.DateTime> PaymentReleaseDate { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreadtedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpadtedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeath> TblDeaths { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEducationHdr> TblEducationHdrs { get; set; }
        public virtual TblFundReleaseOrderHdr TblFundReleaseOrderHdr { get; set; }
        public virtual TblRLOOffice TblRLOOffice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblPaymentReleaseHdr> TblPaymentReleaseHdrs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblProvidentFund> TblProvidentFunds { get; set; }
    }
}
