//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPFCollectionMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblPFCollectionMaster()
        {
            this.TblPFCollectionDtls = new HashSet<TblPFCollectionDtl>();
        }
    
        public long PFCollectionId { get; set; }
        public Nullable<int> AgentNo { get; set; }
        public Nullable<long> BenPFAccountId { get; set; }
        public Nullable<long> BenSno { get; set; }
        public Nullable<decimal> CollectionAmount { get; set; }
        public Nullable<System.DateTime> CollectionDate { get; set; }
        public Nullable<long> BookNo { get; set; }
        public Nullable<long> ReceiptNo { get; set; }
        public Nullable<int> RLOOfficeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblPFCollectionDtl> TblPFCollectionDtls { get; set; }
        public virtual TblRLOOffice TblRLOOffice { get; set; }
        public virtual TblBeneficiary TblBeneficiary { get; set; }
    }
}
