//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPaymentReleaseHdr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblPaymentReleaseHdr()
        {
            this.TblDeaths = new HashSet<TblDeath>();
            this.TblEducationHdrs = new HashSet<TblEducationHdr>();
            this.TblProvidentFunds = new HashSet<TblProvidentFund>();
        }
    
        public long PaymentReleaseId { get; set; }
        public Nullable<long> PaymentProcessingId { get; set; }
        public Nullable<System.DateTime> PaymentReleaseDate { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreadtedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpadtedDate { get; set; }
        public Nullable<int> RLOBankAccountId { get; set; }
        public Nullable<decimal> ReleasedAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeath> TblDeaths { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEducationHdr> TblEducationHdrs { get; set; }
        public virtual TblPaymentProcessingHdr TblPaymentProcessingHdr { get; set; }
        public virtual TblRLOOfficeBank TblRLOOfficeBank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblProvidentFund> TblProvidentFunds { get; set; }
    }
}
