//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPFDepositMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblPFDepositMaster()
        {
            this.TblPFDepositDtls = new HashSet<TblPFDepositDtl>();
        }
    
        public long PFDepositId { get; set; }
        public Nullable<int> AgentNo { get; set; }
        public Nullable<System.DateTime> DepositDate { get; set; }
        public Nullable<decimal> DepositAmount { get; set; }
        public Nullable<int> RLOOfficeId { get; set; }
        public Nullable<int> BankId { get; set; }
        public Nullable<long> PayinSlipNo { get; set; }
        public string TransactionType { get; set; }
        public Nullable<bool> IsPayInSlipUploaded { get; set; }
        public Nullable<long> ScrollNumber { get; set; }
        public Nullable<System.DateTime> BankDepositDate { get; set; }
        public Nullable<int> WorkerTypeId { get; set; }
        public Nullable<int> isPaymentDeposited { get; set; }
        public string GRN { get; set; }
        public Nullable<int> TransactionStatus { get; set; }
        public Nullable<bool> IsGrips { get; set; }
        public Nullable<long> LwcBankCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblPFDepositDtl> TblPFDepositDtls { get; set; }
        public virtual TblRLOOffice TblRLOOffice { get; set; }
        public virtual TblWorkerType TblWorkerType { get; set; }
    }
}
