//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPFCollectionDtl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblPFCollectionDtl()
        {
            this.TblPFDepositDtls = new HashSet<TblPFDepositDtl>();
        }
    
        public long PFCollectionDtlId { get; set; }
        public Nullable<long> PFCollectionId { get; set; }
        public Nullable<int> MonthPaid { get; set; }
        public Nullable<int> YearPaid { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Remarks { get; set; }
        public string BnRemarks { get; set; }
        public string Description { get; set; }
        public Nullable<int> DepositStatus { get; set; }
    
        public virtual TblPFCollectionMaster TblPFCollectionMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblPFDepositDtl> TblPFDepositDtls { get; set; }
    }
}
