//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPostOfficeData
    {
        public int PoSno { get; set; }
        public int DistrictId { get; set; }
        public string PoName { get; set; }
        public string PoPinCode { get; set; }
    }
}
