//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPackage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblPackage()
        {
            this.TblHealthFamilyPackages = new HashSet<TblHealthFamilyPackage>();
        }
    
        public long PackageID { get; set; }
        public string PackageName { get; set; }
        public Nullable<long> AilmentID { get; set; }
        public Nullable<long> PackageCode { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual TblAilment TblAilment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblHealthFamilyPackage> TblHealthFamilyPackages { get; set; }
    }
}
