//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPFDepositDtl
    {
        public long PFDepositDtlId { get; set; }
        public Nullable<long> PFDepositId { get; set; }
        public Nullable<long> BenPFAccountId { get; set; }
        public Nullable<long> BenSno { get; set; }
        public Nullable<long> PFCollectionDtlId { get; set; }
        public Nullable<int> MonthPaid { get; set; }
        public Nullable<int> YearPaid { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> FinancialYearId { get; set; }
    
        public virtual TblBeneficiary TblBeneficiary { get; set; }
        public virtual TblFinancialYear TblFinancialYear { get; set; }
        public virtual TblPFDepositMaster TblPFDepositMaster { get; set; }
    }
}
