//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblRLOOffice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblRLOOffice()
        {
            this.TblFundReleaseOrderHdrs = new HashSet<TblFundReleaseOrderHdr>();
            this.TblFundRequestHdrs = new HashSet<TblFundRequestHdr>();
            this.TblPaymentProcessingHdrs = new HashSet<TblPaymentProcessingHdr>();
            this.TblRLOOfficeBanks = new HashSet<TblRLOOfficeBank>();
            this.TblRLOOfficeUsers = new HashSet<TblRLOOfficeUser>();
            this.TblUtilizationCertificateHdrs = new HashSet<TblUtilizationCertificateHdr>();
            this.TblPFDepositMasters = new HashSet<TblPFDepositMaster>();
        }
    
        public int RLOOfficeId { get; set; }
        public string RLOOfficeCode { get; set; }
        public string RLOOfficeName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreadtedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpadtedDate { get; set; }
        public Nullable<int> SubDivisionId { get; set; }
        public Nullable<int> ALCId { get; set; }
        public string MobileNo { get; set; }
        public string LandlineNumber { get; set; }
        public string EmailId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFundReleaseOrderHdr> TblFundReleaseOrderHdrs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFundRequestHdr> TblFundRequestHdrs { get; set; }
        public virtual TblNewReg TblNewReg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblPaymentProcessingHdr> TblPaymentProcessingHdrs { get; set; }
        public virtual TblSubDivision TblSubDivision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblRLOOfficeBank> TblRLOOfficeBanks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblRLOOfficeUser> TblRLOOfficeUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblUtilizationCertificateHdr> TblUtilizationCertificateHdrs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblPFDepositMaster> TblPFDepositMasters { get; set; }
    }
}
