//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblRLOOfficeUser
    {
        public int RowId { get; set; }
        public Nullable<int> RLOOfficeId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual TblNewReg TblNewReg { get; set; }
        public virtual TblRLOOffice TblRLOOffice { get; set; }
    }
}
