//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblRequiredDoc
    {
        public int Id { get; set; }
        public long Bensno { get; set; }
        public int BenPhoto { get; set; }
        public int BenSignature { get; set; }
        public int BenPassBook { get; set; }
        public int BenAadhar { get; set; }
        public int BenIdentity { get; set; }
        public int BenForm { get; set; }
        public int BenOtherDoc { get; set; }
        public int SchemeCertificate { get; set; }
        public int Status { get; set; }
    }
}
