//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSM
    {
        public long ID { get; set; }
        public Nullable<long> UserId { get; set; }
        public string Message { get; set; }
        public Nullable<int> Status { get; set; }
        public string MessageType { get; set; }
        public string UserType { get; set; }
        public string RequestID { get; set; }
        public string Responseid { get; set; }
        public string ResponseMessage { get; set; }
        public string MobileNum { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ResendDate { get; set; }
    }
}
