//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTransaction
    {
        public int TransLogID { get; set; }
        public int UserID { get; set; }
        public string ServiceRequestID { get; set; }
        public string ServiceResponseID { get; set; }
        public string ConsumerNo { get; set; }
        public string ConsumerName { get; set; }
        public string PaidBy { get; set; }
        public string PaidTo { get; set; }
        public Nullable<int> Tenure { get; set; }
        public string Scheme { get; set; }
        public Nullable<int> PGID { get; set; }
        public string PGRequestID { get; set; }
        public string PGResponseID { get; set; }
        public string PaymentType { get; set; }
        public double BillAmount { get; set; }
        public Nullable<double> UserCharges { get; set; }
        public Nullable<double> ConvienenceFee { get; set; }
        public Nullable<bool> PGTransStatus { get; set; }
        public string StatusCode { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string ip_add { get; set; }
    }
}
