//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUtilizationCertificateHdr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblUtilizationCertificateHdr()
        {
            this.TblUtilizationCertificateDtls = new HashSet<TblUtilizationCertificateDtl>();
        }
    
        public long UtilizationCertificateHdrId { get; set; }
        public Nullable<int> RLOOfficeID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public Nullable<decimal> FundRecieved { get; set; }
        public Nullable<decimal> FundUtilized { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<int> FinancialYearId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> BoardId { get; set; }
    
        public virtual TblFinancialYear TblFinancialYear { get; set; }
        public virtual TblRLOOffice TblRLOOffice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblUtilizationCertificateDtl> TblUtilizationCertificateDtls { get; set; }
    }
}
