//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblWorkFlowDtl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblWorkFlowDtl()
        {
            this.TblClaimStatus = new HashSet<TblClaimStatu>();
            this.TblWorkFlowTransactionSteps = new HashSet<TblWorkFlowTransactionStep>();
        }
    
        public int WFDtlId { get; set; }
        public Nullable<int> WFId { get; set; }
        public string StepName { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string Description { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblClaimStatu> TblClaimStatus { get; set; }
        public virtual TblWorkFlowHdr TblWorkFlowHdr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblWorkFlowTransactionStep> TblWorkFlowTransactionSteps { get; set; }
    }
}
