//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblWorkFlowTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblWorkFlowTransaction()
        {
            this.TblWorkFlowTransactionSteps = new HashSet<TblWorkFlowTransactionStep>();
        }
    
        public long WFTransId { get; set; }
        public Nullable<long> BaseTransactionId { get; set; }
        public Nullable<long> TransactionType { get; set; }
        public Nullable<int> WFId { get; set; }
        public Nullable<int> CurrentWorkFlowSeq { get; set; }
        public Nullable<int> CurrentClaimStatus { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual TblClaimConfigHdr TblClaimConfigHdr { get; set; }
        public virtual TblClaimStatu TblClaimStatu { get; set; }
        public virtual TblWorkFlowHdr TblWorkFlowHdr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblWorkFlowTransactionStep> TblWorkFlowTransactionSteps { get; set; }
    }
}
