//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblWorkFlowTransactionStep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblWorkFlowTransactionStep()
        {
            this.TblWorkflowTransactionLogs = new HashSet<TblWorkflowTransactionLog>();
        }
    
        public long WFTransactionStepId { get; set; }
        public Nullable<long> WFTransId { get; set; }
        public Nullable<int> WFStepId { get; set; }
        public Nullable<int> WorkFlowSeq { get; set; }
        public Nullable<long> Userid { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<System.DateTime> TrasanctionDate { get; set; }
        public Nullable<int> StepStatus { get; set; }
        public Nullable<System.DateTime> TransClosureDate { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual TblWorkFlowDtl TblWorkFlowDtl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblWorkflowTransactionLog> TblWorkflowTransactionLogs { get; set; }
        public virtual TblWorkFlowTransaction TblWorkFlowTransaction { get; set; }
    }
}
